### ISSUE TITLE
Package is not installable from pypi

### ISSUE THREAD

**Issue by skirpichev** [logpy/strategies#2]
```
$ mkvirtualenv test
New python executable in test/bin/python
Installing distribute.............................................................................................................................................................................................done.
Installing pip...............done.
virtualenvwrapper.user_scripts creating /home/sk/.virtualenvs/test/bin/predeactivate
virtualenvwrapper.user_scripts creating /home/sk/.virtualenvs/test/bin/postdeactivate
virtualenvwrapper.user_scripts creating /home/sk/.virtualenvs/test/bin/preactivate
virtualenvwrapper.user_scripts creating /home/sk/.virtualenvs/test/bin/postactivate
virtualenvwrapper.user_scripts creating /home/sk/.virtualenvs/test/bin/get_env_details
$ pip install strategies
Downloading/unpacking strategies
  Downloading strategies-0.2.0.tar.gz
  Running setup.py egg_info for package strategies
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/home/sk/.virtualenvs/test/build/strategies/setup.py", line 10, in <module>
        install_requires=open('dependencies.txt').read().split('\n'),
    IOError: [Errno 2] No such file or directory: 'dependencies.txt'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/home/sk/.virtualenvs/test/build/strategies/setup.py", line 10, in <module>

    install_requires=open('dependencies.txt').read().split('\n'),

IOError: [Errno 2] No such file or directory: 'dependencies.txt'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /home/sk/.virtualenvs/test/build/strategies
Storing complete log in /home/sk/.pip/pip.log
$ python --version
Python 2.7.3
```

**Comment by mrocklin** [comment]
Dependencies wasn't in the MANIFEST.  Fixed and pushed to PyPI.

**Comment by skirpichev** [comment]
Works for me.  Thank you, I'll close this bugreport.
